### ISSUE TITLE
開発チームとして，テストマニュアルが欲しい．それは，テストのやり方をまとめることでテストの作成を効率的に進めたいからだ．

### ISSUE THREAD

**Issue by rihito-bannai** [sclab-dev/website#10]
- [x] ソフトウェアテストと教科書を読み、テストについてマニュアルを書く

### テスト設計はするがテストドキュメントはテストコードが代替
アジャイルはイテレーションが短く、詳細なテストドキュメントを作成する時間はないため、開発時と同じようにテストコードがテストドキュメントの代わりとなる。ただテスト設計に関してはウォーターフォールと変わらず詳細に行うこと。テスト設計も省略していいというわけではない。

**Comment by CreFa** [comment]
後で読みます。ありがとうございます。
