### ISSUE TITLE
開発チームとして，テストが欲しい．それは，開発前にテストを作成することでTDDを行うためだ．

### ISSUE THREAD

**Issue by rihito-bannai** [sclab-dev/website#101]
- [x] 基本設計
  - [x] サイトマップを作る
  - [x] ワイヤーフレームを作る
  - [x] URL設計

- [ ] システム・機能テスト
  - [x] テスト対象機能一覧作成
  - [x] テスト観点一覧表作成
  - [x] テストマップ作成
  - [ ] 機能動作確認一覧作成
  - [ ] テスト明細作成
  - [ ] テストケース作成

- 前に作ったブログがどこに記事内容を保存しているのか調べる。コードをローカルに落としてきて、ローカルで立ち上げたブログ上で記事を作成した時、どこにその情報がストックされるか

- サムネイル生成機能は画像は縦横比を最初の時点で合わせているのでwidthをパラメータにして大きさを変える

- 機能一覧で新たに出た機能はissueに加える

- システム機能テストは実装できるものはコード書く

- 機能テストの遷移テストのやり方について調べる

**Comment by rihito-bannai** [comment]
当初、システムテストと機能テストをやるつもりでしたが、システムテストと機能テストは後に回すことができるのと、予定が進まなそうなので、基本設計書の作成は終了したことからこのissue は一旦閉じて早めに単体テストの作成と実装の方に移りたいと思います。

[基本設計書](https://docs.google.com/document/d/1klDrZGWUmiz0QmNPzlg80q07lZXepWXIHHQcvHZOQZ8/edit?usp=sharing)
[機能一覧](https://docs.google.com/spreadsheets/d/1xi_BbYHxB42OiJWmDDY1c-pR3mbeflPQrxd1gPRc_po/edit?usp=sharing)

**Comment by CreFa** [comment]
承知しました。
