### ISSUE TITLE
同じ開発者として，このissueの指示（このissueの説明に記載）に従って新規issueの作成からクローズまでをチュートリアルとしてやってほしい．それは，スクラムに則って開発を進められるようになって欲しいからだ．

### ISSUE THREAD

**Issue by rihito-bannai** [sclab-dev/website#110]
### やって欲しいこと
（Bootstrapの導入も兼ねて）一通り，新規issueを立ててからクローズの持って行くまでの流れを体験して欲しいので，bootstrapを使って簡単に1ページ作成してみるということを下記の「流れ」に従ってやってみてください．作成するページは雑で構いません．

### 流れ
1. [x] ロードマップとエピックを見て全体としてどのような流れで開発が進もうとしていて，自分がやらなければいけないことはなんなのか把握する
2. [x] 自分がやらなければいけないことを具体的に落とし込み．それに基づいてissueをNew issue上に作成する（issueのタイトルはユーザストーリ形式で書くこと．書き方はNotionの「スクラム実行マニュアル」に載っている）
3. [x] 坂内がNew issue上にissueが追加されているのを確認したら優先順位をつけてProductBacklogに移すので，うつされたことを確認したら受け入れ基準，完成の定義を書き，見積もりを出し（相対見積もりになるので坂内の見積もりと基準を合わせるため，見積もりを出す段階になったら坂内に基準を聞く），DevelopmentBacklogに移動させる．
4. [x] 坂内がDevelopmentBacklog上のissueを特定のスプリントに追加し，SprintBacklogに移動させる
5. [x] SprintBacklogに移動されたissueを上からやっていく．このとき，取り組んでいるissueは自分をアサインした上でIn Peogressに移動させる．issueをチェックボックスを使ってさらに細かくタスクに分割する．
6. [ ] issueが終わったらDoneに移し，坂内にPRを出す．
7. [ ] 坂内がPRの確認を終えたら，坂内がそのissueをクローズする．

**Comment by rihito-bannai** [comment]
すいません，上記の流れは誤りを含んでいたので，#125に取り組む際は，#154にあるマニュアルに書かれている流れを参考にやってください．

**Comment by rihito-bannai** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/website-625e104d63d96f0014fac708/issues/sclab-dev/website/110?planning-poker) with ZenHub @CreFa

**Comment by CreFa** [comment]
一通りの流れを体験するという本来の目的は達成できているので、reviewに回します
