### ISSUE TITLE
開発チームとして，サイトで一部使われているdocxファイルをPDFファイルに統一してもいいか把握したい．それは，ファイルの拡張子がバラバラなのは管理がめんどくさいので新しいサイトを実装する際にPDFファイルに統一したいからだ．

### ISSUE THREAD

**Issue by rihito-bannai** [sclab-dev/website#114]
中国語研究室の人にdocxファイルをPDFファイルとして提供する形ではダメなのか聞く．

サイトで使われているdocxファイルは全てPDFファイルで代用できるように思える．海外渡航の誓約書も手書きのサインが必要になるのでワードで編集する必要性のあるファイルがないように思える．PDFファイルに統一する形ではダメなのか．

- Task list
- [x] CNSサーバーにログインして、ファイルを取得できる状況を作る
- [x] 先生に問い合わせをする（ccに児玉さんと趙さんを入れる）

--------------------------------

本件、pdf変換してもOKとの返信を受領済み。

**Comment by rihito-bannai** [comment]
すいません，ちょっとissueの書き方が悪かったですね．新しいサイトを実装する際にdocxファイルをPDFファイルにしてもいいか聞いてほしいだけで，現状のサイトでdocxファイルをPDFファイルに変換することは考えていません

**Comment by CreFa** [comment]
了解です！ありがとうございます

**Comment by rihito-bannai** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/website-625e104d63d96f0014fac708/issues/sclab-dev/website/114?planning-poker) with ZenHub @CreFa

**Comment by CreFa** [comment]
docxをpdfに変換して掲載しても大丈夫との返信をいただきました。

**Comment by rihito-bannai** [comment]
ありがとうございます．
