### ISSUE TITLE
開発チームとして現サイトで確認されたセキュリティの脆弱性を修正したい．それはサイトが攻撃されないようにするためだ．

### ISSUE THREAD

**Issue by rihito-bannai** [sclab-dev/website#119]
https://china-lab.sfc.keio.ac.jp/?s=%22%3E%3Cscript%3Ealert()%3C/script%3E
これが、エクスプロイトコードなのですが、s=のあとに任意のjavascriptをインジェクションできます。これはXSS攻撃と呼ばれるので修正しておいたほうが懸命です。

例えば、悪意のある人間が、中国語研究室のURLを共有しようとするときに、同じドメインなので信用できると思いきや別のサイトに遷移させるみたいなことができちゃいます。 

なので、Javascriptで扱う< > = " 'などの記号が検索されるときにその文字を別の文字に置き換えるなどの対策が必要

**Comment by rihito-bannai** [comment]
この状態で何年もサイトが運営されてきたことを踏まえ，緊急性は低いと判断．新しく作るサイトでカバーすることとし（#53 ），旧サイトにおいては取り組まないこととした．

**Comment by CreFa** [comment]
リニューアル後に対応すること、承知いたしました。任意のJSコードが実行できてしまうことも理解しました。
ありがとうございます。
