### ISSUE TITLE
開発チームとしてCNSサーバに入れるようにしたい．それはサーバ上で作業をするためだ

### ISSUE THREAD

**Issue by rihito-bannai** [sclab-dev/website#121]

**Comment by rihito-bannai** [comment]
@CreFa 無事ssh接続できました．接続する際に参考にしたリソースなどをまとめた[ドキュメント](https://docs.google.com/document/d/1cjHqGw1Bn6ipjdn6uN2Z7Ni1T9rElGIZ4COPb14E3vQ/edit?usp=sharing)を作成しましたので確認お願いします．

**Comment by CreFa** [comment]
ありがとうございます。
私も先ほどCNSガイドを確認してやってみたのですが、すでにSSH接続できている状態でした。
SSH接続がどのようなものかをあまり理解できていませんでした。失礼しました。

**Comment by rihito-bannai** [comment]
@CreFa クローズお願いします
