### ISSUE TITLE
開発チームとしてWordpressのパスワードなどが欲しい．それはワードプレスのコードなどを触るためだ

### ISSUE THREAD

**Issue by rihito-bannai** [sclab-dev/website#122]

**Comment by CreFa** [comment]
聞きました。返答待ちです。

**Comment by rihito-bannai** [comment]
ありがとうございます．わかったらGoogleDriveにその情報を置いて欲しいです．あとWordpressのパスワードとかはセンシティブな情報なのでDMで聞いた方がよかったかと思います．

**Comment by rihito-bannai** [comment]
CNSサーバ情報とかWordpressのパスワードとか変更するissueを立ててもらえないでしょうか．

**Comment by CreFa** [comment]
コメントありがとうございます。
Driveに載せました。

wordpressのパスの件に関しては私の不覚でした。すみません。
（そもそも、パスワードがおそらく「管理員」をピンインにしただけの簡単なpassでして、結構破られそうな感じがする）
CNSサーバ情報は多分フォルダへのアクセス権を向こうで制御していて、ディレクトリの場所自体はCNSにログインできる人は全員見えるので特に問題ないと思います。

**Comment by rihito-bannai** [comment]
了解です．ありがとうございます．CNSサーバ情報に関しては承知しました．issueを閉じておきます．

現在のWordpressのパスワードの強化はしなくてもいいかと思います．そもそもこの状態で何年もサイトが運営されていたことと，他にもセキュリティの脆弱性を発見したので，，，

あとdriveに上げているwordpressのログイン情報ですが，CNSサーバ情報とは別の場所に保存できますでしょうか．理由としては，①wordpressはサーバではないので「サーバ情報」に入れるのは混乱を招く，②wordpressから今後移行していくので，今後も使っていくであろうCNSサーバと同じ場所に書いておくのは管理上よくない，からです．

以上，よろしくお願いします．

**Comment by CreFa** [comment]
ありがとうございます。ご指摘いただいた件、対応しました。

**Comment by rihito-bannai** [comment]
ありがとうございます．
