### ISSUE TITLE
開発者として、Bootstrapでデザインしたwebページを1枚作る。それは、bootstrapを触っておき、サイトのデザインを実装するときにすぐに始められるように、加えて実装にかかる時間を短縮するためだ。

### ISSUE THREAD

**Issue by CreFa** [sclab-dev/website#125]
- [x] Bootstrapを学ぶページを探し、決める。（公式ドキュメント等を中心に、素早く知識を得られるページを制定）
 - [x] 坂内さんに、Bootstrapを実際のWebページにはどのように導入するのか（CDN or ダウンロード）を聞く。加えて、どちらが速いのか、メリットがあるのかを調べる。実際に導入する方式に近い形式でBootstrapを導入し、制作の準備を整える。
 - [x] 適当なダミーデータをどこかから引っ張り、Bootstrapを使った簡単なページを作成する

-------------------------
坂内さんに聞いた結果：
CDNだと世界中にサーバーがあるので、各利用者が近いところからライブラリを取ってくるので速い（要リサーチではある）

時間があればアイコンも入れたい。

**Comment by rihito-bannai** [comment]
- bootstrapでページを作るときにVScodeのLiveShareという拡張機能が便利です

- 「bootstrapの知識を身に付ける」というのは曖昧なので具体的に達成したい作業内容に直してください．今回やる作業は「Bootstrapでデザインしたwebページを1枚作る」ことなのでそれをそのまま書いてください．

- 「それは」の後はこのissueをやる目的を書きます．「スムーズな開発に支障をきたす」からやるでは曖昧なので．「サイトのデザインを実装する際にすぐに作業を開始できるようにする」ためのようにもう少し具体的に書いた方がいいです．

**Comment by CreFa** [comment]
添削いただきありがとうございます！
修正します。

**Comment by rihito-bannai** [comment]
あ，あとこのissueはフロントエンドのissueなので「フロントエンド」のラベルをこのissueに追加してもらってもいいでしょうか．ラベルは後でどの領域の作業をどれぐらいやったのかを調べるのに役立つのでお願いします．

**Comment by rihito-bannai** [comment]
#110のコメントを見てからこのissueに取り組んでください

**Comment by rihito-bannai** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/website-625e104d63d96f0014fac708/issues/sclab-dev/website/125?planning-poker) with ZenHub @CreFa

**Comment by rihito-bannai** [comment]
ちなみにダミーデータを引っ張ってくる必要はないと思います．必要であれば「あああ」とか「aaa」とかで文字を埋めて，画像が必要なら1枚の画像を使いまわせばいいかと思います

**Comment by CreFa** [comment]
https://web.sfc.keio.ac.jp/~t19656sf/bootstrap_test/
あまり時間をかけられていませんが、現時点でできているものを共有します

**Comment by rihito-bannai** [comment]
ありがとうございます．これって今ページ幅全体に表示されているのを一定のページ幅に収めることはできますか？

あとこのweb.sfc.keio.ac.jpというドメインはどういうやつですかね

**Comment by CreFa** [comment]
幅についてですが、やり方を調べて対応したいと思います。

CNSのサーバに学生各個人がファイルをWebに公開できる領域を持っていて、そちらに仮にあげている状態です。（public_htmlというフォルダです）

**Comment by rihito-bannai** [comment]
あっ，そうなんですね，知らなかったです．でしたらそこを開発サーバにしちゃうことも考えちゃっていいですね

**Comment by CreFa** [comment]
@rihito-bannai 
https://web.sfc.keio.ac.jp/~t19656sf/bootstrap_test/
↑を更新しました。
一通り、bootstrapの使い方や基本的概念は理解できたと考えています。
もしこれでよければ、closeお願いします。

**Comment by rihito-bannai** [comment]
一点だけ、フッターが気になりました。フッターがビューポートの一番下に表示されるようにできないでしょうか。

**Comment by CreFa** [comment]
コメントありがとうございます。
フッターを表示領域の一番下に表示させるようにしました。
加えて、ヘッダーも追従させるようにしてみました。

**Comment by rihito-bannai** [comment]
ありがとうございます
