### ISSUE TITLE
スクラムマスターとして，現在のプロジェクトでの具体的なスクラムの実行方法をマニュアルにまとめる．それは形式化することでスクラムの実施コストを下げ，かつ一定の質を担保するためだ．

### ISSUE THREAD

**Issue by rihito-bannai** [sclab-dev/website#154]
- [x] マニュアルを作成する
- [x] 実施しやすいようにスライドでテンプレートを作る

**Comment by rihito-bannai** [comment]
@CreFa レビューをお願いします．
レビューの仕方は下記マニュアルに記載してます

マニュアル（このURLの「ウェブサイトスクラム実行マニュアル」．このURLは今後このプロジェクトのWikiにしようと思っているので保存しておいてください）→https://www.notion.so/rihib/SFC-adeb2d574632479fa1fda08e11047c7b

スライドのテンプレート→GoogleDriveの「テンプレート」に入ってます．

**Comment by CreFa** [comment]
@rihito-bannai 
遅くなりすみません。レビューをさせて頂きました。
スライドにコメントも付けてあります。邪魔だったらすみません。（スライドにレビューをするときはコメントをつけるか、こちらにレビューを書くかを統一するとやりやすい気はしました。）
私の疑問や感想ばかりで申し訳ないのですが、以下に挙げさせていただきます。

------------------------------------------

【テンプレート3】7スライド目、リリースに関して：
リリース日までの80%というのがよくわからないのですが、例えば現在4月1日で6月1日リリース予定であれば、5月18日までがリリース作業をするリリース期間ということでしょうか？
（私自身、リリースという単語の意味があまりよくわかっていない気もしてきました。。。。）

【テンプレート5】7,10スライド目
リリース日までの80%というのがよくわからないのですが、例えば現在4月1日で6月1日リリース予定であれば、5月18日までがリリース作業をするリリース期間ということでしょうか？
（私自身、リリースという単語の意味があまりよくわかっていない気もしてきました。。。。）

**Comment by rihito-bannai** [comment]
リリース期間というのはリリースに持っていける状態にするまでの作業という意味です．

**Comment by CreFa** [comment]
お話も伺い、疑問点が解決しました。
ありがとうございます。
