### ISSUE TITLE
スクラムチームとして，ステークホルダーのメールアドレスの一覧が欲しい．それはステークホルダー全員と円滑に連絡を取りたいからだ．

### ISSUE THREAD

**Issue by rihito-bannai** [sclab-dev/website#157]
ステークホルダー（先生方やSAの方）とメールをするときに毎回個々人がそれぞれ手動でccを設定していると，抜けがあったり，時間のロスがあったりするので，Google Driveにステークホルダー全員のメールアドレスとそれに対応する本名，役職が載っているドキュメントを作ってほしい．

宛先(cc)を複数設定するときの書式：
`sho0101@gmail.com, fukuzaki@keio.jp`

**Comment by rihito-bannai** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/website-625e104d63d96f0014fac708/issues/sclab-dev/website/157?planning-poker) with ZenHub @CreFa

**Comment by CreFa** [comment]
@rihito-bannai 
作成しました。レビューお願いします。
簡易的なものなのでその点はご容赦ください。

https://docs.google.com/spreadsheets/d/1QC8crLli-D40acfBfNLclY9H8qDA5DME6e_QqwL9E_E/edit#gid=0

**Comment by CreFa** [comment]
鈴木さんもccに入れるようにしています。

**Comment by rihito-bannai** [comment]
了解です．ありがとうございます．とても使いやすそうです🙇‍♂️
