### ISSUE TITLE
開発チームとして，Wordpressのパスワードを変更したい．現在研究室内で誰でも見える状態になっているのでセキュリティ上よくないからだ．

### ISSUE THREAD

**Issue by rihito-bannai** [sclab-dev/website#159]
#122 

SAリーダー、鈴木さん、先生方に連絡を取り、wordpressを編集しているSAや先生方を把握し、パスワードを変更しても問題ないかを聞く。
その後、変更したパスワードを特定の人にのみ共有する。

**Comment by rihito-bannai** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/website-625e104d63d96f0014fac708/issues/sclab-dev/website/159?planning-poker) with ZenHub @CreFa

**Comment by CreFa** [comment]
@rihito-bannai 
パスワードの変更が完了し、趙さんと鈴木さんに個別に連絡しました。
新しいパスワードは以下のファイルに追記しましたが、bitwardenにも追加したほうがよいでしょうか？

https://docs.google.com/document/d/1_sLb3_lOrzj3xit_HoDwWLCCt0fYhiRmlPOWry_IACw/edit

**Comment by rihito-bannai** [comment]
パスワードはbitwardenで一括管理したいので、そのドキュメントは削除して、bitwardenの方に追加してください。その際、予備用アカウントのユーザ名・パスワード情報は一緒に管理したいので本アカウントのメモ欄に入力してください。

**Comment by CreFa** [comment]
了解です。

**Comment by CreFa** [comment]
すみません、collectionに追加する権限がない？みたいで追加できないのですが、どのように追加すればいいですか？

![image](https://user-images.githubusercontent.com/55471518/167255660-2919d0d7-1054-4cab-b588-3d09b4d4a0fd.png)

**Comment by rihito-bannai** [comment]
こちらで追加しておきました。確認できましたら、Googleドキュメントの方は削除しておいてください。

**Comment by CreFa** [comment]
確認しました。ありがとうございます。

**Comment by rihito-bannai** [comment]
ありがとうございます。確認しました
