### ISSUE TITLE
スクラムチームとして，スクラムをマニュアルの形式に直す．それは形式化したスクラムのやり方に則ることでスクラムを効率的に進めていくためだ．

### ISSUE THREAD

**Issue by rihito-bannai** [sclab-dev/website#160]
#154 で作成したマニュアルとスライドに則る形に変更する

- [x] GoogleDriveを「プロジェクト > リリース > スプリント」の階層に整理する
- [x] Google Driveのディレクトリ構造についてドキュメントにまとめる
- [x] マニュアルに沿ってスクラムの管理をやり直す（スライドの再作成も含む）

**Comment by rihito-bannai** [comment]
#124 をこのissueに統合したため，見積もりを変更

**Comment by rihito-bannai** [comment]
マニュアルに沿って，スクラムの形式を直しました．具体的には，見積もりやスライドの作成などを行いました．

**Comment by CreFa** [comment]
スクラムマニュアルを読み、理解できました。
作成ありがとうございました。
