### ISSUE TITLE
SFC中国語研究室として，ユーザ行動を分析できるツールを導入して欲しい．それは，古いサイトとリニューアルされたサイトのユーザ行動の変化を測定することで効果を測定するためだ．

### ISSUE THREAD

**Issue by rihito-bannai** [sclab-dev/website#174]
Google Analyticsなど？
古いサイトの方でも比較のためにデータを取る必要があるのでできるだけ早く導入するのが望ましい

**Comment by rihito-bannai** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/website-625e104d63d96f0014fac708/issues/sclab-dev/website/174?planning-poker) with ZenHub @CreFa

**Comment by rihito-bannai** [comment]
@CreFa すいません，#65 や#125 で忙しくなる前に一旦このissueを片付けてもらってもいいでしょうか．リリースまで時間がないので信頼性のあるデータの確保のためにも早めに導入しておきたいです．

**Comment by CreFa** [comment]
@rihito-bannai 返信遅くなり申し訳ないです。
承知しました。wordpressにAnalyticsを導入します。

導入にあたり、アカウントはどうしましょうか。
sfc.chinalab.dev@gmail.com
のアカウントでAnalyticsを導入するのであれば、パスワードを教えて頂けると嬉しいです。

**Comment by rihito-bannai** [comment]
了解です．後でメールを確認してください．

**Comment by CreFa** [comment]
メール確認しました。ありがとうございます

**Comment by CreFa** [comment]
@rihito-bannai bitwardenのorganizationへの承認申請？が今できたと思いますが、いっていますか？
（初めてであまりわからず、、できてなかったらすみません。）

**Comment by rihito-bannai** [comment]
ありがとうございます．こちらで承認しました．確認お願いします

**Comment by CreFa** [comment]
ありがとうございます！
wordpressにプラグインを導入し、
[sfc.chinalab.dev@gmail.com](mailto:sfc.chinalab.dev@gmail.com)
のアカウントで導入完了しました。

詳細な設定は未了ですが、動作確認は済んでいます。
ひとまずはこれで大丈夫そうでしょうか。
![image](https://user-images.githubusercontent.com/55471518/166129112-a6c2a755-388e-44ee-af53-c52aae5b7214.png)

**Comment by rihito-bannai** [comment]
ありがとうございます．僕はGoogleAnalyticsをちゃんと使った経験がないのですが， @CreFa さんは使い方を知ってますか？

**Comment by CreFa** [comment]
私も、きちんと使った経験はないです。
期間を指定して、どのページにどのような属性の人はどのくらいのアクセスが来ているかを把握するなどはしたことがあります。

**Comment by rihito-bannai** [comment]
データは一定期間は保存されているんでしたっけ．別途保存しないと消えてしまうデータ項目があるのか，保存されるデータ項目はどれぐらいの期間保存されるのか調べてくれませんか．

**Comment by CreFa** [comment]
わかりました。
私が使っている限りデータが消えるということはなかったと思いますが、後ほどきちんと調べてご報告します。

**Comment by CreFa** [comment]
すみません、個別のユーザのデータのイベントデータは最長14か月で消えるみたいです。
デフォルトが2か月に設定されていたので、14か月に伸ばしておきました。
![image](https://user-images.githubusercontent.com/55471518/166150522-b2748264-dcaf-4d4f-b120-095d388f303b.png)

**Comment by rihito-bannai** [comment]
了解です
