### ISSUE TITLE
スクラムチームとして，good first issueに関して見積もりポーカーをしてほしい．それは，複数人の視点から見積もりをすることでより精度を高めるためだ．

### ISSUE THREAD

**Issue by rihito-bannai** [sclab-dev/website#180]

**Comment by rihito-bannai** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/website-625e104d63d96f0014fac708/issues/sclab-dev/website/180?planning-poker) with ZenHub @CreFa

**Comment by rihito-bannai** [comment]
@CreFa 自分をアサインしてIn Progressに移動させてください

**Comment by CreFa** [comment]
good first issueのものは全て見積もりをしたように思いますが、こちらはreviewに回して大丈夫でしょうか？

**Comment by rihito-bannai** [comment]
大丈夫です👍

**Comment by CreFa** [comment]
ありがとうございます！

**Comment by rihito-bannai** [comment]
👍
