### ISSUE TITLE
開発チームとして、先生方から（インセプションデッキレビューと質問の）メールの返信が来たら、現在の成果でわかりやすいものを返信したい。それは、スプリントレビューを代替し、かつ適切な関係性を保つためだ。

### ISSUE THREAD

**Issue by CreFa** [sclab-dev/website#181]
スプリントレビューの代替的意味も込めて、連絡する。

例：todoリスト作成とか、サイト構造を作ったとか

**Comment by CreFa** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/website-625e104d63d96f0014fac708/issues/sclab-dev/website/181?planning-poker) with ZenHub @rihito-bannai

**Comment by CreFa** [comment]
返信しましたので、レビューお願いします。

**Comment by rihito-bannai** [comment]
OKです．ありがとうございます👍
