### ISSUE TITLE
開発チームとして、勤務時間のスプレッドシートを作り、児玉さんに共有したい。児玉さんへ都度作業時間を送る手間を軽減し、開発やスクラムの運営に集中するためだ。

### ISSUE THREAD

**Issue by CreFa** [sclab-dev/website#182]
https://docs.google.com/spreadsheets/d/1spvLLIPHQF9yv2VeoQ7pN8kPG0E9dWoXpzH_6ySQIFc/edit?usp=sharing

**Comment by rihito-bannai** [comment]
ラベルと見積もりポーカーを始めてください．他のNew issueについても同様にお願いします．

**Comment by rihito-bannai** [comment]
見積もりポーカーはこのissueの右側にあるEatimateという項目で「Add members to vote」をクリックして，見積もりポーカーに参加する人を選んで自分の見積りを入力してください

**Comment by CreFa** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/website-625e104d63d96f0014fac708/issues/sclab-dev/website/182?planning-poker) with ZenHub @rihito-bannai

**Comment by CreFa** [comment]
コメントありがとうございます。
お送りいただいた件、対応しました。

**Comment by CreFa** [comment]
https://docs.google.com/spreadsheets/d/1spvLLIPHQF9yv2VeoQ7pN8kPG0E9dWoXpzH_6ySQIFc/edit?usp=sharing

**Comment by CreFa** [comment]
レビューお願いしたいです。
良ければ児玉さんに送ります。

**Comment by CreFa** [comment]
@rihito-bannai

**Comment by rihito-bannai** [comment]
大丈夫です。お願いします
