### ISSUE TITLE
中国語研究室のシラバスを閲覧したい学生として、Wordpressでサイドバーの表示の問題が出てくる箇所を修正してほしい。それは、見栄えに瑕疵のない状態で、最新のシラバスのリンクを取得したいからだ。

### ISSUE THREAD

**Issue by rihito-bannai** [sclab-dev/website#191]
【経緯が複雑なので、整理】
「シラバス」ページにおいて、学校の公式シラバスリンクのリンク切れがあるため、修正したい。
しかし、当該ページ（「シラバス」ページ）を更新しようとすると、左サイドバーがサイトの下部に移動してしまう問題がある。
そのため、この問題を解決し、正しい学校の公式シラバスリンクを閲覧者に提供したい。

【問題の経過と原因予想】
「シラバス」ページの左サイドメニューが下になってしまう問題を模索してみましたが、サイドメニューのコード自体には異常はなさそうです。
そこで、更新前と更新後の差分を見てみると、文法的におかしい方がきちんと表示されていました。根深い問題なので、緩和策を含め、後々時間をかけて検証したいです。
（左が正常）

![image](https://user-images.githubusercontent.com/55471518/166188737-e4c04ae9-b353-4f9f-bd99-18daeb670765.png)

**Comment by CreFa** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/website-625e104d63d96f0014fac708/issues/sclab-dev/website/191?planning-poker) with ZenHub @rihito-bannai

**Comment by rihito-bannai** [comment]
以下の理由からこのissueには取り組まない方がいいのではと思いました。

- 今学期の終わり頃に新しいサイトになる
- このissueの解決にはそこそこのリソースがとられる
- 新しいサイトのタスクが多くあまりリソースを割くことができない
- 内容自体には問題なく、上記の点を差し置いてまでやるほどの価値があると思えない

**Comment by CreFa** [comment]
同意します。
解決するまでにどのくらいの作業量が必要なのか不透明なのでやらないほうがいいと私も感じます。
