### ISSUE TITLE
開発チームとして再見積もりしたい．それは，見積もり時間を実際の時間に近づけることで見通しを正確にするためだ．

### ISSUE THREAD

**Issue by rihito-bannai** [sclab-dev/website#192]
- [x] スプリントも直す
- [x] リリースレポートを確認

**Comment by rihito-bannai** [comment]
再度全てのissueのポイントを見積もり直し（ポイントを現実的なラインにまで増やしました），

いくつかのissueをプロダクトバックログから外しました（主にデプロイ周り．一旦nginxやdockerを使わずdjangoだけでリリースしてみようと思います）．

またスプリントも割り振り直しました．

@CreFa

**Comment by CreFa** [comment]
ありがとうございます。
#106 についてですが、サイトのデータ移行を行い、現サイトでは統一性がなく大変なことになっているタグ構造を整え、アクセス権などの設定をするとなると、かなり時間がかかると思いました。（これらの作業は、他のissueにわかれていたりするのでしょうか？）
djangoによる開発経験がないため、的外れなことを言っていたらごめんなさい。

**Comment by rihito-bannai** [comment]
最初は個人のアカウント機能をつけない方向で行こうと思います。なので、あらかじめ備わっている管理者ユーザのみと、静的ページのみの最小限の機能でまずはリリースしようと思っているので、現在のページをコピペするだけになるため、そこまでの時間はかからないかなと思っています。

ブログや個人ごとのアカウント機能は初期リリース後に様子を見て随時実装していくつもりです。

**Comment by CreFa** [comment]
ありがとうございます！承知しました。
ご説明をいただき、確かにそれであれば時間はあまりかからないと私も感じましたので、closeします。
