### ISSUE TITLE
中国語研究室の情報を知りたい学生として、SA一覧と教員一覧に関して、誤りのない最新の情報が欲しい．それは，中国語を履修するにあたり、SAや教員の情報を正確にしりたいからだ．

### ISSUE THREAD

**Issue by CreFa** [sclab-dev/website#195]
鈴木さんと連絡を取り、以下のページの修正をお願いする。

- [ ] SA紹介
- [ ] 教員紹介

**Comment by rihito-bannai** [comment]
issueタイトルは個人の依拠した形ではなく、タスクベースで書いてください。「誤りのない最新の情報が欲しい」だと曖昧すぎて、粒度が荒いので、具体的なタスクごとにissueを分割してください。

一つのissueは数日以内で終わるぐらいのサイズが望ましいです。

あくまでAsigneesによって担当者を指定するので、issueタイトルで担当者を指名するのは柔軟性に欠けます。

**Comment by rihito-bannai** [comment]
それで大丈夫です。粒度が細かすぎてしまうかもしれませんが、適切な大きさにまとめられないならまだ小さくまとめた方がいいと思います（柔軟性が上がる、見積の精度が高まる、いつまでもissueが閉じない事態を避けられる、issueが曖昧になるのを防げるなどから）。

**Comment by CreFa** [comment]
了解です

**Comment by CreFa** [comment]
#196 と同様にcloseしたいです。

**Comment by rihito-bannai** [comment]
直接移動させてしまって大丈夫です。
