### ISSUE TITLE
中国語研究室の情報を知りたい学生として、最新かつ正確な追加コンテンツが欲しい．それは、中国語を履修するにあたり、追加コンテンツや研究会紹介等を閲覧することで中国語や研究室に対する理解を向上させるためだ。

### ISSUE THREAD

**Issue by CreFa** [sclab-dev/website#196]
宮本先生から資料を頂いて、更新するコンテンツ

- [ ] 研究会紹介
- [ ] 全体図
- [ ] 音読チャイニーズ

**Comment by rihito-bannai** [comment]
#195 と同様です

**Comment by CreFa** [comment]
@rihito-bannai 
#199 #200 #201 に分割したのでこのissueをcloseしたいのですが、new issueパイプラインからreview/QAパイプラインに直接移動させて大丈夫ですか？

**Comment by rihito-bannai** [comment]
大丈夫です。issueに取り組まずにクローズさせたい場合は直接動かしてもらって大丈夫です。

**Comment by CreFa** [comment]
承知しました。ありがとうございます。
