### ISSUE TITLE
中国語を履修している学生として、ondoku chineseのリンクをまとめたページが欲しい。単語なども含め、全ての学習用コンテンツを中国語研究室ホームページからシームレスに閲覧したいからだ。

### ISSUE THREAD

**Issue by CreFa** [sclab-dev/website#199]
データは提供済みなのですぐに作業可能

↓掲載済み↓
https://china-lab.sfc.keio.ac.jp/ondoku-chinese/

**Comment by CreFa** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/website-625e104d63d96f0014fac708/issues/sclab-dev/website/199?planning-poker) with ZenHub @rihito-bannai

**Comment by rihito-bannai** [comment]
これって新しく追加を要望されているコンテンツですか？

**Comment by CreFa** [comment]
そうです。宮本先生から追加を要望されているもので、先日メールでリンクを送信していただきました。

**Comment by CreFa** [comment]
reviewに回したいので、sprint backlogに移していただきたいです。
お忙しいところ恐縮ですがよろしくお願いします。

**Comment by rihito-bannai** [comment]
サイトコンテンツに関しては確かに運用に含まれますが、システム面での運用との区別をつけるために、サイトコンテンツというラベルを独立して作っているので、システム面での運用以外のissueに関しては運用・監視・保守のラベルはつけないようにお願いします

**Comment by CreFa** [comment]
了解です

**Comment by CreFa** [comment]
パスワード保護はなしにして、宮本先生からいただいた説明も掲載しました。reviewお願いします
https://china-lab.sfc.keio.ac.jp/ondoku-chinese/
