### ISSUE TITLE
サイト利用者として、ヘッダー・フッター・上に戻るボタンのデザインが欲しい。それは、サイトの各ページを円滑に閲覧するためだ。

### ISSUE THREAD

**Issue by rihito-bannai** [sclab-dev/website#207]
bootstrap
- [ ] ヘッダー・フッター・上に戻るボタン

https://web.sfc.keio.ac.jp/~t19656sf/ch-front/

**Comment by CreFa** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/website-625e104d63d96f0014fac708/issues/sclab-dev/website/207?planning-poker) with ZenHub @rihito-bannai

**Comment by CreFa** [comment]
@rihito-bannai 
in progressに回したいので、sprint backlogに移していただきたいです。
お忙しいところ恐縮ですがよろしくお願いします。

**Comment by rihito-bannai** [comment]
#212 でコメントした内容と同じ変更をお願いします。

**Comment by CreFa** [comment]
https://web.sfc.keio.ac.jp/~t19656sf/ch-front/
現在の進捗状況です

**Comment by CreFa** [comment]
@rihito-bannai 進捗度としては、それぞれのパーツの配置が完了し、微修正をしていくだけといった状況です。
この件に関して、数点質問があります。

https://web.sfc.keio.ac.jp/~t19656sf/ch-front/

 - 現状、figmaのデザインと見比べると、上のメニューバーの文字色が違っているという問題点があります。上のメニューバーの文字色やフォントサイズを変えるには、個別にCSSを設定する必要があります。bootstrapで全て実装するということはできなくなってしまい、工数も増えてしまいますが、個別にCSSを設定して文字色やフォントサイズ等を調整しても大丈夫でしょうか。
 - 現状、上のメニューバーの「SFC 中国語履修者専用ホームページ 言語コミュニケーション科目 | 中国語」という文言が、画面幅が小さくなると表示がされなくなっています。こちらは要修正だと認識はしていますが、そもそもスマホ版にこの文言は必要なのか（ハンバーガーメニューの中身が冗長になってしまわないか）という懸念もあります。なので、この段階で対応するべきかも含め、ご意見を頂きたいです。
 - 右下の"上に戻る"ボタンですが、figma上でデザインされていたアイコンがbootstrapのアイコンには存在せず、便宜的に似ているアイコンを載せてあります。私としては上へ戻るボタンの形はデザイン性に大きな影響を与えないことと、手間や実装の簡便さを考えると、このアイコンで実装する方向にしていただけるとありがたいのですが、どうでしょうか。もともとは、figmaのデザインをレビューするときに、そのアイコンがbootstrapで実装可能かを精査することが漏れていたことが原因なので、申し訳ないです。

**Comment by rihito-bannai** [comment]
> 進捗度としては、それぞれのパーツの配置が完了し、微修正をしていくだけといった状況です。

こんな感じでOKです。

> 現状、figmaのデザインと見比べると、上のメニューバーの文字色が違っているという問題点があります。上のメニューバーの文字色やフォントサイズを変えるには、個別にCSSを設定する必要があります。bootstrapで全て実装するということはできなくなってしまい、工数も増えてしまいますが、個別にCSSを設定して文字色やフォントサイズ等を調整しても大丈夫でしょうか。

余裕が出たらやっていきたいとは思いますが、優先順位的には低いので一旦細かいけど工数がかかるような部分については無視して大枠だけ完成させることを目指してください。後々やる必要がある細かい修正についてはissueを新たに立てるようにお願いします。

> 現状、上のメニューバーの「SFC 中国語履修者専用ホームページ 言語コミュニケーション科目 | 中国語」という文言が、画面幅が小さくなると表示がされなくなっています。こちらは要修正だと認識はしていますが、そもそもスマホ版にこの文言は必要なのか（ハンバーガーメニューの中身が冗長になってしまわないか）という懸念もあります。なので、この段階で対応するべきかも含め、ご意見を頂きたいです。

これについてもひとつ上のものと同様に後で考えましょう。こちらもissueを立てておいてください。

> 右下の"上に戻る"ボタンですが、figma上でデザインされていたアイコンがbootstrapのアイコンには存在せず、便宜的に似ているアイコンを載せてあります。私としては上へ戻るボタンの形はデザイン性に大きな影響を与えないことと、手間や実装の簡便さを考えると、このアイコンで実装する方向にしていただけるとありがたいのですが、どうでしょうか。もともとは、figmaのデザインをレビューするときに、そのアイコンがbootstrapで実装可能かを精査することが漏れていたことが原因なので、申し訳ないです。

こちらも現時点では、このままで大丈夫です。Figmaのデザインが絶対というわけではない（私もわりかし適当に作ってる）ので大枠さえ似ていれば大丈夫です。

**Comment by CreFa** [comment]
ありがとうございます。
細かい修正をするissueを新規に立てたので、このissueは完了という方向にさせていただきたいです。

確認遅くなりすみません。
