### ISSUE TITLE
サイト利用者として、トップページから各ページに遷移するためのボタンデザインが欲しい。それは、各ページに遷移して詳細なコンテンツを閲覧するためだ。

### ISSUE THREAD

**Issue by CreFa** [sclab-dev/website#209]
研究室について
カリキュラムについて
学習コンテンツ

カルーセルのサムネイル表示参考サイト：
https://homupedia.com/bootstrap4-carousel.html

画像の上にテキスト：
https://getbootstrap.jp/docs/5.0/components/card/#image-overlays

**Comment by CreFa** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/website-625e104d63d96f0014fac708/issues/sclab-dev/website/209?planning-poker) with ZenHub @rihito-bannai

**Comment by rihito-bannai** [comment]
#212 でコメントした内容と同じ変更をお願いします。

**Comment by CreFa** [comment]
https://web.sfc.keio.ac.jp/~t19656sf/ch-front/
現在の進捗状況です。

**Comment by CreFa** [comment]
@rihito-bannai 
https://web.sfc.keio.ac.jp/~t19656sf/ch-front/
大体完成したのでレビューお願いします。
