### ISSUE TITLE
開発チームとして，開発チームで相談してデザインを決めたい．それは，統一したデザインを最初に決めることで以後のデザイン開発をデザインの大きな変更なくスムーズに行うためだ．

### ISSUE THREAD

**Issue by rihito-bannai** [sclab-dev/website#33]
中国語研究室なので赤色をテーマカラーにしたい
二人で相談して決めましょう

参考サイトリスト
- [Kinsta](https://kinsta.com/jp/blog/)
一番参考になりそう

- [Bootstrap](https://getbootstrap.jp/docs/5.0/getting-started/introduction/)
見やすい，わかりやすい，シンプル

- [Wappalyzer](https://www.wappalyzer.com/)

- [ZenHub](https://help.zenhub.com/support/home)
ZenHubのこういうデザインは最近のモダンなサイトデザインの流行り．

- [airbnb](https://www.airbnb.jp/)
デザインを重視している企業として有名

- [mybest](https://my-best.com/)
トップページはこんな感じがいいかも

**Comment by rihito-bannai** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/website-625e104d63d96f0014fac708/issues/sclab-dev/website/33?planning-poker) with ZenHub @CreFa

**Comment by rihito-bannai** [comment]
@CreFa Canvaの招待リンクを送りました

**Comment by rihito-bannai** [comment]
#35

**Comment by CreFa** [comment]
こちらはレビューする必要があるのでしょうか…？

**Comment by rihito-bannai** [comment]
もちろん、あります。妥当かどうか確認してください

**Comment by CreFa** [comment]
「開発チームで相談してデザインを決める」というissueなので、相談して決めていないのにissueをレビューする、ということがよくわからないです。
方針をレビューするということでしょうか？
それとも、このコメント欄で話し合って決める、ということでしょうか？

**Comment by rihito-bannai** [comment]
duplicateタグがついていているのでこれはコメントにある#35 と内容が被っているのでクローズする形です。
