### ISSUE TITLE
開発チームとして，SlackでもらったCNSサーバ情報をGoogleDriveに保存して欲しい．それはデプロイ時にサーバ情報をすぐに取得したいからだ．

### ISSUE THREAD

**Issue by rihito-bannai** [sclab-dev/website#40]

**Comment by rihito-bannai** [comment]
issueが終わったらReview/QAパイプラインにissueを移し，僕にPRを投げてください．作ったPRはこのissueと紐づけてください．Review/QAにissueがあるのを僕が確認したらレビュー後，僕がdoneに移動させたり，クローズさせるので直接issueをクローズするのはやめてください

**Comment by CreFa** [comment]
ご指摘ありがとうございます。
学習不足で申し訳ないのですが、このような”具体的な成果物が伴わないタスク”ではPull Requestをする必要があるのですか？

**Comment by rihito-bannai** [comment]
あっ，そうですね，この場合はPRではなくてissueのコメント欄で大丈夫ですね．なので一度終わったことをコメント欄で教えていただければと思います．よろしくお願いします．

先ほどGoogle Driveにあるのを確認しましたので，このissueはクローズします👍

**Comment by CreFa** [comment]
ありがとうございます～！
