### ISSUE TITLE
開発チームとして， SFC中国語研究室とインセプションデッキの内容のすり合わせをしたい． それはSFC中国語研究室の要望を正確に把握し，認識のずれを無くしたいたいためだ．

### ISSUE THREAD

**Issue by rihito-bannai** [sclab-dev/website#55]
- [x] 華先生にもわかるようにインセプションデッキの内容をわかりやすく書き直したものを作る（現状，華先生にはインセプションデッキの内容がわからないと言われているため）
- [x] 簡略化し補足を加えたインセプションデッキを坂内さんにチェックしてもらう
- [x] 華先生に改訂版をメール送信
- [ ] メールでやりとりして，内容について修正コメントをもらう
- [ ] 開発チーム内でその修正内容を共有（連絡ください）し，開発チームでインセプションデッキを修正

↑返信を再確認したところ華先生も理解をされていて、特に突っ込みはなかったので、問題ないと判断しreviewに回します。

**Comment by CreFa** [comment]
タスクを追加してほしいです：
-[ ] 簡略化し補足を加えたインセプションデッキを坂内さんにチェックしてもらう

**Comment by rihito-bannai** [comment]
自分がアサインされたissueなのでタスクについては自由に変えてもらっていいですよ！

**Comment by CreFa** [comment]
@rihito-bannai 
https://docs.google.com/presentation/d/1BgjYWMJkUEqJpor4GyElbEIzcLGoewFu/edit#slide=id.p2
こちらの、わかりやすいように簡略化＋補足追加したインセプションデッキを華先生含む先生陣に送ってしまっても大丈夫ですか？一回送る前に坂内さんに確認していただきたいです！

（この質問を投げるべき場所が違っていたらすみません）

**Comment by rihito-bannai** [comment]
> （この質問を投げるべき場所が違っていたらすみません）
全然大丈夫ですよ！むしろどんどん積極的に動いたり，発言をしちゃってください．コミュニケーションを積極的に取るのがスクラムなので（ラグビーのスクラムのようにメンバーでがっちり協力し合あうのが名前の由来）

以下コメントです．

- [ ] 宮本先生のコメントもコピーされちゃってるので消してください
- [ ] 2枚目の「優先的に取り組む課題」のスライドはいらないと思うのですがどうでしょうか．インセプションデッキはプロジェクトの理念みたいな抽象的で根本的な部分に対する認識を揃えるためのものなので，個別のタスクに言及するのは違うかなと思います．
- [ ] 4枚目「新しいWebサイトの全体像の整理」と5枚目「新Webサイトの利点と特徴（イメージ）」は多分今のままだと華先生が拒否反応を示すと思うので，4枚目と5枚目は1枚のスライドにまとめて，こういうイメージでサイトを作り替えようとしてますよということを箇条書きでまとめちゃってください
- [ ] 7枚目「使う技術の概要」も拒否反応を示されると思うので削除しちゃってください
- [ ] 8枚目「私たちの“チーム”」はメンバーの名前と役割（僕と福崎さんは「開発者」，鈴木さんは「サポート役」）だけシンプルに書いたものにしちゃってください．多分このままだとわかんないと言われてしまうので
- [ ] 9枚目「スケジュール」は公開予定日だけ書いたのを載せるだけでいいです．細かいことを書くとわかんないと言われてしまうので（画像も消す）
- [ ] 10~12枚目は全て削除しちゃって大丈夫です．

**Comment by CreFa** [comment]
@rihito-bannai 
ありがとうございます。ご指摘の点を修正しました。
「優先的に取り組む課題」のスライドですが、インセプションデッキからは削除しました。
しかし、あちらの希望はサイトのコンテンツ更新から先に動くことなので、「こちらはサイトのリニューアルに向けての認識揃えのためであり、あくまでもコンテンツ更新を最優先で行います」のような文面をメールに入れ、双方の認識の齟齬をなくしたいです。
以上でいかがでしょうか。

**Comment by rihito-bannai** [comment]
了解です．お願いします．

**Comment by rihito-bannai** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/website-625e104d63d96f0014fac708/issues/sclab-dev/website/55?planning-poker) with ZenHub @CreFa

**Comment by CreFa** [comment]
これまでの返信を再確認したところ華先生も理解をされていて、特に突っ込みはなかったので、問題ないと判断しreviewに回します。
よろしくお願い致します。

**Comment by rihito-bannai** [comment]
アサインはレビューする人がレビューする時になったらやるので自分でアサインはしないでください．現在レビュー中なのかそうでないかの区別がすぐにつかなくなってしまうので

**Comment by rihito-bannai** [comment]
ありがとうございます

**Comment by CreFa** [comment]
すみません、、
