### ISSUE TITLE
開発チームとして，リリースまでの見積もりが欲しい．それは進捗の目安を持つことでリリースまでissueを管理するためだ．

### ISSUE THREAD

**Issue by rihito-bannai** [sclab-dev/website#64]
- [x] 新たな見積もり用のワークスペースを作成し，SBIを大中小で分けて，基準を決め，それぞれのissueの見積もりをする（既にクローズしたissueの見積もりもする）

**Comment by CreFa** [comment]
対面でご説明いただき理解できました。
見積りも問題ないかと思います。ありがとうございます。
