### ISSUE TITLE
中国語研究室の情報を知りたい学生として、誤りのない最新の情報が欲しい．それは，中国語を履修するにあたり新旧情報が混在することによる混乱を避けたいからだ．

### ISSUE THREAD

**Issue by rihito-bannai** [sclab-dev/website#65]
シラバスリンク等の細かい修正を行い、最新の情報にアップデートする（福崎担当分）

- [x] 履修ガイド（学校公式）のリンク切れ
- [ ] シラバス（学校公式）のリンク切れ→右サイドバーが下になるバグにより修正不可
- [x] FAQの左サイドメニュー「コンピュータで中国語」がない
- [x] 「当サイトについて」の内容が古い
- [x] 自習室の内容が古い（時限等）
- [x] 「SFC科挙について」情報が古い

サイドバーの表示の問題が出るページは一旦更新を保留にして他のページの更新をする

以下、変更前
------------------------------------

> 例えば、講師紹介、SA紹介、研究会紹介、全体図の部分は、更新が必要です。具体的には、こちらで資料を用意します。また、現在ある自習用のコンテンツについては、そのまま移植をお願いします。そのほか、４月からOndoku ChineseというWebアプリを使用し始めたので、そのリンクをはるページも必要です。コンテンツは今後も増やす予定ですが、少し時間が必要です。 by 宮本先生

宮本先生から上記の要望があったので，それに対応してほしい．
具体的には以下をやってほしい．
- 宮本先生と相談して更新したいコンテンツを把握する
- 鈴木さんと協力して，今のサイト上でコンテンツの内容を最新のものに変更する
- 新規に追加したURLや削除したURLがあったら逐一必ず教えてください．新しいサイトに移行するURLを把握しておく必要があるからです

タスクリスト
- [x] 中国語研究室のWebサイトをくまなくチェックし、現状と齟齬があるところを探し、記録する
- [x] ↑で挙げられた点と宮本先生からの要望をリスト化し、それを修正するのにはどのような情報が必要なのか、それは学生だけでできる範囲なのかを考え、文章化する
- [x] 鈴木さんに、wordpressの更新ができるのか、どのくらいの作業量ができるのかを確認する
- [x] 宮本先生にメールを送る
- [ ] 鈴木さんに作業を割り振る
- [ ] 承認を得られ次第順次修正していく

**Comment by rihito-bannai** [comment]
In Progress以外のissueのasigneesを解除したので，今後は「good first issue」タグがついているissueを中心に自分でできそうだと思うissueを選んで（自分をアサインして）進めてください．

**Comment by rihito-bannai** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/website-625e104d63d96f0014fac708/issues/sclab-dev/website/65?planning-poker) with ZenHub @CreFa

**Comment by CreFa** [comment]
現在、メール返信待ち

**Comment by CreFa** [comment]
現在、鈴木さんの返信待ち

**Comment by CreFa** [comment]
間違えてcloseしてしまいました… ごめんなさい

**Comment by rihito-bannai** [comment]
大丈夫ですよ．僕もよくやります

**Comment by CreFa** [comment]
@rihito-bannaiissueを分けてみました。どうでしょうか。

**Comment by CreFa** [comment]
FAQの左サイドメニュー修正は元のPHPファイルを編集し、修正しました。
wordpress上でPHPファイルを編集しようとするとエラー吐くので、編集して直接サーバにアップロードしました。

扱うところが近かったので「シラバス」ページの左サイドメニューが下になってしまう問題を模索してみましたが、サイドメニューのコード自体には異常はなさそうです。
そこで、更新前と更新後の差分を見てみると、文法的におかしい方がきちんと表示されていました。根深い問題なので、緩和策を含め、後々時間をかけて検証したいです。
（左が正常）

![image](https://user-images.githubusercontent.com/55471518/166187882-65cac277-109f-41d2-b83a-8a004523cc77.png)

**Comment by CreFa** [comment]
@rihito-bannai 
サイドメニューの問題が発生している箇所以外は、私に割り振っている更新作業を終了したのでレビューお願いします

**Comment by rihito-bannai** [comment]
サイドバーの問題は#191 としてissueを立てたので，そちらに移譲してください．

**Comment by CreFa** [comment]
了解です

**Comment by rihito-bannai** [comment]
すいません，「履修ガイド（学校公式）のリンク切れ」とはどの部分でしょうか

**Comment by CreFa** [comment]
ごめんなさい、大変不親切でした、、

履修ガイドのリンク切れ：https://china-lab.sfc.keio.ac.jp/curriculum/intensive-course/
FAQ：https://china-lab.sfc.keio.ac.jp/faq/

です。よろしくお願いします。

**Comment by rihito-bannai** [comment]
FAQの「コンピュータで中国語」のメニューって追加されてますか？僕の方だと確認できないです

**Comment by CreFa** [comment]
ごめんなさい！表現がおかしかったです。
コンピュータで中国語に関する質問がなかったので、「コンピュータで中国語」にというメニューを削除しているということです、、
他にも、左サイドメニューの見出しが右のコンテンツ部の見出しと対応していないところがあったので、修正しています。

**Comment by CreFa** [comment]
@rihito-bannai

**Comment by rihito-bannai** [comment]
了解です．ありがとうございます
